### ISSUE TITLE
Enum casing

### ISSUE THREAD

**Issue by BasThomas** [jhurray/Transform.swift#1]
Hi,

I was wondering if you intentionally used `PascalCase` for the enum values? As of Swift 3, the new convention will be to use `camelCase` for enum values.

I think it might be a good idea to change it now, also because of the fact the library reads like functions are getting called, where those functions are `PascalCase`... which does not make sense.

**Comment by jhurray** [comment]
Thanks for the heads up. As discussed privately i will definitely be making these changes once swift 3 actually arrives.
